### ISSUE TITLE
Prospector

### ISSUE THREAD

**Issue by diraol** [cemsbr/yala#133]
Hey @cemsbr , have you seen [prospector](https://pypi.org/project/prospector/) ?

It looks like both yala and Prospector aim to do the same thing. Which are the main differences?

**Comment by cemsbr** [comment]
I took a quick look at prospector. Indeed, our aims are quite similar. Besides minor differences like linters and their settings (easy to be changed), I'll list some major differences that is far from an exhaustive list:
1. Prospector uses linters through Python code and I've seen bad consequences such as quite old dependencies in pylama and different default settings in coala. Yala captures linters' outuput to overcome these problems;
1. You don't have to learn new options and new ways to configure linters with yala: just check the linters' docs and write their own INI configs or CLI options in `setup.cfg` yala section - no extra file needed;
1. You may also agree that yala is easier to maintain, since it has 300 lines of Python code and prospector has 2799 lines + 600 YAML lines (considering master branches with cloc, by the time of this writing);
1. I'm not 100% sure, but it seems that prospector doesn't parallelize linter checks, so yala can be faster specially in larger projects.
1. Prospector has more features than yala. You may prefer it if yala is missing a feature you need. In this case, please, create an issue with the feature request.

Those were quick impressions that I had and, please, feel free to correct me (anybody) if I'm wrong or misunderstood prospector in any way.
